name: GregLouis
favicon: null
layout_spectrum: 0.7668675119057298
typography_spectrum: 0.6621940934564918
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.4185814065858722
  lightness: 0.1633899377193302
  saturation: 0.7818288167472929
  rhythmicContrast: 0.16174252680502832
purpose: []
